name: Kalshi â€“ Past Bids w/ PnL

on:
  schedule:
    # every 12 hours;
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  run-kalshi-past-bids:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread google-auth cryptography

      - name: Write Google service account file
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Run Kalshi past bids script
        env:
          KALSHI_API_KEY_ID: ${{ secrets.KALSHI_API_KEY_ID }}
          KALSHI_PRIVATE_KEY_PEM: ${{ secrets.KALSHI_PRIVATE_KEY_PEM }}
        run: |
          python kalshi_past_bids_winfo.py
